### ISSUE TITLE
Search time string 'unavailable'

### ISSUE THREAD

**Issue by vredesbyyrd** [fogine/rofi-google#2]
Rofi's message box for reporting 'search time' is only displaying:

`about <unavailable> results (<unavailable> seconds)` 

Not a big deal, just figured I would report it while I am here.  I do wonder if its something with my environment but have yet to figure it out. 

EDIT: Read over this my first time through doc: 

> (ddgr, googler) ...does not parse information about number of search results so this information is not currently available when using this method

Assuming that why, issue can be closed...sorry.

**Comment by fogine** [comment]
This is mentioned in the `readme` and currently it's a limitation of external dependencies `googler` and `ddgr` , they do not parse the information at all.  
So  currently search count results and search time data are available when using Google custom search engine `cse` method only...  

To fix this I'd have to implement my own scraper and keep it up to date.  
For the time being I want to keep it lightweight...
I guess I'd accept PR in the future which would add another custom search method that would scrape for the results on its own but that would require splitting the project into multiple files and having build script on release...

**Comment by vredesbyyrd** [comment]
> For the time being I want to keep it lightweight...

Absolutely. 

Ill take a look at the `cse` method.

**Comment by alizehctl** [comment]
Is there any way to disable the search time string?

**Comment by fogine** [comment]
I guess the information about the search time being unavailable is useless so I can remove it all together in that case..
