### ISSUE TITLE
wish: support passing a custom browser command

### ISSUE THREAD

**Issue by markstos** [fogine/rofi-google#4]
I use a "work profile" and a "personal profile" and I might want to open a search result in either.

Also, a custom browser command could be used to launch an Incognito search. 

The custom browser command may contain spaces, as itself might include options passed to a browser binary.

**Comment by fogine** [comment]
> I use a "work profile" and a "personal profile" and I might want to open a search result in either.

How that is related to `rofi-search`, what do you mean by opening a search result in "work profile" or "personal profile", @markstos ?

> Also, a custom browser command could be used to launch an Incognito search.
The custom browser command may contain spaces, as itself might include options passed to a browser binary.

Yes, I'll provide an option for that, thank you for the suggestion.

**Comment by fogine** [comment]
> I use a "work profile" and a "personal profile" and I might want to open a search result in either.

If I mapped another shortcut, `-kb-custom-2` to another user defined command, would that provide the solution for you?  

Meaning, when pressing `enter` you would do normal search defined by `ROFI_SEARCH_COMMAND` with fallback to `xdg-open` and when pressing `-kb-custom-2`, `rofi-search` would execute different command defined by `ROFI_SEARCH_COMMAND_CUSTOM`..

**Comment by markstos** [comment]
Thanks for the reply. I was thinking that if I wanted to use a non-default browser, I would bind a second key to launch rofi-search with different args:

    `rofi-search --browser="firefox --profile='alt'"`

I don't think `rofi-search` needs to add support for alternate key bindings internally.
