### ISSUE TITLE
Odd output

### ISSUE THREAD

**Issue by mtwb47** [fogine/rofi-google#5]
For whatever reason when I use this the output comes through fairly garbled. 
This is what it looks like. https://imgur.com/5NIG007  

This is the command I'm using. 

```
rofi -modi blocks -blocks-wrap /usr/bin/rofi-search -show blocks \ 
-lines 4 -eh 4 -kb-custom-1 'Control+y' -theme /usr/share/rofi/themes/glue_pro_blue.rasi
```

I'm guessing that it's either a font problem or I'm missing a dependency. I'm not sure which is most likely. I installed through the AUR.

**Comment by mtwb47** [comment]
![ArcoLinux_2020-10-05_10-56-10](https://user-images.githubusercontent.com/32562514/95096198-f6131080-06f9-11eb-8220-e4e1e2026eeb.png)


I added the screenshot here, as imgur is bad.

**Comment by fogine** [comment]
I think the issue will be in your rofi theme. Try to run it with the theme I'm using and see if the issue persists.
https://github.com/fogine/dotfiles/blob/master/rofi/google_theme.css

**Comment by mtwb47** [comment]
Changing the theme didn't work. This is the command I ended up with.
```

rofi -modi blocks -blocks-wrap /usr/bin/rofi-search -show blocks \ 
-lines 4 -eh 4 -kb-custom-1 'Control+y' -theme /usr/share/rofi/themes/glue_pro_blue.rasi
```

I get a shell error: 

`command not found: -lines`

The output is still the same and the theme didn't actually change at all. I tried also to go through and change the theme to something else, and it still stuck with the same thing, so something is obviously off with rofi, and not this script. I'll figure it out.

**Comment by fogine** [comment]
Did you resolve the issue @mtwb47 ? if not try to provide parameters in the following exact order:
> rofi -modi blocks -show blocks -lines 4 -eh 4 -kb-custom-1 'Control+y' -theme /path/to/theme.rasi -blocks-wrap /usr/bin/rofi-search

if that still doesnt work, you have old or broken version of `rofi` installed on your system

**Comment by fogine** [comment]
Closing this for lack of response. Feel free to reopen.
