### ISSUE TITLE
[support] Add keyboard shortcut (xfce4)

### ISSUE THREAD

**Issue by tracure1337** [fogine/rofi-google#7]
Hello,

Thanks for this great piece of software.

But I fail to map it to a hotkey in xfce4.

How would I go about this ? I'd like to use ddgr.

rofu itself works great and all needed dependencies are installed.

**Comment by fogine** [comment]
Glad that you find it useful.  
Setting global hotkey in xfce environment is out of the scope of this application.
You can follow one of many tutorials on the internet, for example:
https://www.unixmen.com/how-to-add-shortcut-keys-in-xfce/

If you decide to follow the above tutorial, you would then fill in the  `path/to/rofi-search` on your system to the command input box when creating a new shortcut..  

If you wanna use ddgr, make sure that the ddgr package is installed on your system and use the most recent version of `rofi-search` from master branch..

**Comment by fogine** [comment]
Closing due to lack of response.
