### ISSUE TITLE
rofi-search spawns rofi

### ISSUE THREAD

**Issue by marcbenedi** [fogine/rofi-google#8]
Greetings,

For what I could find, `rofi-search` spawns internally `rofi` which makes it incompatible with the provided examples.

```
$ rofi -modi blocks -blocks-wrap rofi-search -show blocks

(process:773472): Helper-WARNING **: 00:15:00.469: Failed to set lock on pidfile: Rofi already running?

(process:773472): Helper-WARNING **: 00:15:00.469: Got error: -1 Socket operation on non-socket
BlocksMode-Message: 00:15:00.474: Child 773464 exited normally
```

![image](https://user-images.githubusercontent.com/17215876/142948868-a9e3f464-27a1-4737-8d30-f0ee50cbae1a.png)

![image](https://user-images.githubusercontent.com/17215876/142949167-84e79681-6813-4457-b749-57a998ec9e72.png)

Is there a solution for that? If `rofi-search` spawns `rofi` internally, it would be nice to be able to pass arguments to `rofi`. Otherwise `rofi` should not be launched internally.

**Comment by fogine** [comment]
It needs `ROFI_SEARCH` env variable set (as shown in the readme examples)  prior executing rofi command.
Just copy paste one of the provided examples and edit it to your needs..

**Comment by marcbenedi** [comment]
I specified the variable `ROFI_SEARCH` as you specified and it works.
However, in the documentation they only say that this variable is to specify the search tool, but it seems that it's actually mandatory to define it.
