### ISSUE TITLE
not able to open link in browser

### ISSUE THREAD

**Issue by kmehtab** [fogine/rofi-google#9]
not able to open search results in the browser. I have added -kb-accept-entry but nothing happens I am able to copy the URL by pressing control+y.

**Comment by fogine** [comment]
if you did not set `ROFI_SEARCH_CMD` env variable as described in readme, it will call `xdg-open <url>` with selected url.
So investigate if `xdg-open` is setup to open urls on your system.

**Comment by fogine** [comment]
also if you press `enther` or other key you configured as `-kb-accept-entry` and nothing happens, that means `-kb-accept-entry` is configured incorrectly.. if its configured correctly then it should close the rofi application window. if rofi application windows closes after selecting entry but no url is opened in the browser, then look into the `ROFI_SEARCH_CMD` env variable as mentioned above.
